#!/usr/bin/env bash
# Circuit Breaker — One-Line Installer
# Usage: curl -fsSL https://raw.githubusercontent.com/BlkLeg/CircuitBreaker/main/install.sh | bash
# Docs:  https://github.com/BlkLeg/CircuitBreaker
set -euo pipefail

# ── Native install dispatch ──────────────────────────────────
if [ "${CB_INSTALL_MODE:-}" = "native" ]; then
    # Download and run the native installer
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    if [ -f "$SCRIPT_DIR/deploy/native/install.sh" ]; then
        exec "$SCRIPT_DIR/deploy/native/install.sh" "$@"
    else
        echo "Native installer not found locally. Downloading..."
        curl -fsSL https://raw.githubusercontent.com/BlkLeg/CircuitBreaker/main/deploy/native/install.sh | bash
        exit $?
    fi
fi
# ─────────────────────────────────────────────────────────────

# ── Config ──────────────────────────────────────────────────
CB_VERSION="${CB_VERSION:-latest}"
CB_PORT="${CB_PORT:-80}"
CB_INSTALL_DIR="${CB_INSTALL_DIR:-$HOME/.circuitbreaker}"
COMPOSE_URL="https://raw.githubusercontent.com/BlkLeg/CircuitBreaker/main/docker-compose.yml"

# ── Colors ──────────────────────────────────────────────────
RESET="\033[0m"; BOLD="\033[1m"; GREEN="\033[32m"
ORANGE="\033[33m"; RED="\033[31m"; DIM="\033[2m"
ok()   { echo -e "  ${GREEN}✓${RESET} $*"; }
info() { echo -e "  ${DIM}→${RESET} $*"; }
warn() { echo -e "  ${ORANGE}⚠${RESET} $*"; }
die()  { echo -e "  ${RED}✗${RESET} $*" >&2; exit 1; }

# ── Header ───────────────────────────────────────────────────
clear
echo -e "${BOLD}${ORANGE}"
cat <<'BANNER'
   ___  _                   _ _   ___
  / __\(_)_ __ ___ _   _(_) |_  / __\_ __ ___  __ _| | _____ _ __
 / /   | | '__/ __| | | | | __| /__\// '__/ _ \/ _` | |/ / _ \ '__|
/ /____| | | | (__| |_| | | |_/ \/  \ | |  __/ (_| |   <  __/ |
\______|_|_|  \___|\__,_|_|\__\_____/_|  \___|\__,_|_|\_\___|_|
BANNER
echo -e "${RESET}"
echo -e "  Homelab topology, documented.  ${DIM}https://github.com/BlkLeg/CircuitBreaker${RESET}"
echo

# ── Check: Docker ────────────────────────────────────────────
info "Checking for Docker..."
command -v docker >/dev/null 2>&1 || die "Docker is not installed.
    Install it first: https://docs.docker.com/get-docker/"
docker info >/dev/null 2>&1 || die "Docker daemon is not running. Start it and retry."
ok "Docker $(docker --version | awk '{print $3}' | tr -d ',')"

# Check docker compose (v2 plugin)
if ! docker compose version >/dev/null 2>&1; then
    die "Docker Compose V2 is required. Update Docker Desktop or install the plugin:
    https://docs.docker.com/compose/install/"
fi
ok "Docker Compose $(docker compose version --short)"

# ── Setup install dir ─────────────────────────────────────────
mkdir -p "$CB_INSTALL_DIR"
info "Install directory: $CB_INSTALL_DIR"

# ── Download docker-compose.yml ──────────────────────────────
info "Downloading docker-compose.yml..."
curl -fsSL "$COMPOSE_URL" -o "$CB_INSTALL_DIR/docker-compose.yml"
ok "docker-compose.yml downloaded"

# ── Generate .env if not present ──────────────────────────────
ENV_FILE="$CB_INSTALL_DIR/.env"
if [ ! -f "$ENV_FILE" ]; then
    info "Generating secrets..."

    JWT_SECRET=$(python3 -c "import secrets; print(secrets.token_hex(32))" 2>/dev/null \
        || openssl rand -hex 32)
    VAULT_KEY=$(python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" 2>/dev/null \
        || openssl rand -base64 32)
    DB_PASS=$(python3 -c "import secrets; print(secrets.token_urlsafe(24))" 2>/dev/null \
        || openssl rand -base64 18)
    NATS_TOKEN=$(openssl rand -base64 32)

    cat > "$ENV_FILE" <<EOF
# Circuit Breaker — generated by install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT SHARE this file. It contains your secrets.

CB_JWT_SECRET=${JWT_SECRET}
CB_VAULT_KEY=${VAULT_KEY}
CB_DB_PASSWORD=${DB_PASS}
NATS_AUTH_TOKEN=${NATS_TOKEN}
CB_PORT=${CB_PORT}
CB_PORT_HTTPS=${CB_PORT_HTTPS:-443}
CB_IMAGE=ghcr.io/blkleg/circuitbreaker:mono-${CB_VERSION}
EOF
    chmod 600 "$ENV_FILE"
    ok "Secrets generated and saved to $ENV_FILE"
else
    ok ".env already exists — using existing secrets"
    CB_PORT=$(grep -E '^CB_PORT=' "$ENV_FILE" 2>/dev/null | cut -d= -f2- | tr -d '"' | head -1) || true
    CB_PORT=${CB_PORT:-80}
fi

# ── Fix volume ownership if upgrading from root container ────────────
if docker volume inspect circuitbreaker-data >/dev/null 2>&1; then
    info "Existing volume detected — checking ownership..."
    OWNER_UID=$(docker run --rm -v circuitbreaker-data:/data alpine stat -c '%u' /data 2>/dev/null || echo "1000")
    if [ "$OWNER_UID" -eq 0 ]; then
        warn "Volume is owned by root (uid 0) — fixing permissions for non-root operation..."
        docker run --rm -v circuitbreaker-data:/data alpine sh -c "chown -R 1000:1000 /data && chmod -R 750 /data && chmod 700 /data/pgdata 2>/dev/null || true"
        ok "Volume ownership fixed (now 1000:1000)"
    else
        ok "Volume ownership is correct (uid $OWNER_UID)"
    fi
fi

# ── Pull and start ────────────────────────────────────────────
info "Pulling image..."
cd "$CB_INSTALL_DIR"
docker compose --env-file "$ENV_FILE" pull

info "Starting Circuit Breaker..."
docker compose --env-file "$ENV_FILE" up -d

# ── Wait for health ───────────────────────────────────────────
info "Waiting for Circuit Breaker to be ready..."
TRIES=0
until curl -sf "http://localhost:${CB_PORT}/api/v1/health" >/dev/null 2>&1; do
    TRIES=$((TRIES + 1))
    [ $TRIES -ge 30 ] && die "Health check timed out. Check logs:
    docker compose --project-directory $CB_INSTALL_DIR logs"
    sleep 2
done
ok "Circuit Breaker is healthy"

# ── Get LAN IP ────────────────────────────────────────────────
LAN_IP=$(ip -4 addr show scope global 2>/dev/null \
    | awk '/inet/{print $2}' | cut -d/ -f1 | head -1 \
    || hostname -I 2>/dev/null | awk '{print $1}' \
    || echo "localhost")

# ── Welcome ───────────────────────────────────────────────────
echo
echo -e "  ${BOLD}${GREEN}Circuit Breaker is running!${RESET}"
echo
echo -e "  ${BOLD}Open in your browser:${RESET}"
echo -e "    → http://${LAN_IP}:${CB_PORT}"
echo -e "    → http://localhost:${CB_PORT}"
echo
echo -e "  ${DIM}First launch: the setup wizard will create your admin account.${RESET}"
echo
echo -e "  ${BOLD}Manage:${RESET}"
echo -e "    Stop:    ${DIM}docker compose --project-directory $CB_INSTALL_DIR down${RESET}"
echo -e "    Logs:    ${DIM}docker compose --project-directory $CB_INSTALL_DIR logs -f${RESET}"
echo -e "    Update:  ${DIM}curl -fsSL https://raw.githubusercontent.com/BlkLeg/CircuitBreaker/main/install.sh | bash${RESET}"
echo -e "    Config:  ${DIM}$ENV_FILE${RESET}"
echo
