bind 127.0.0.1
port 6379
protected-mode yes
requirepass ${CB_REDIS_PASS}
timeout 0
tcp-keepalive 300
daemonize no
supervised systemd
pidfile /var/run/redis/redis-server.pid
loglevel notice
logfile ${CB_DATA_DIR}/logs/redis.log
databases 16
save 900 1
save 300 10
save 60 10000
stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes
dbfilename dump.rdb
dir ${CB_DATA_DIR}/redis
maxmemory ${redis_maxmem}
maxmemory-policy allkeys-lru
appendonly no
