export const HARDWARE_ROLES = []; // See useHardwareRoles for the dynamic catalog
export const HARDWARE_ROLE_LABELS = {};

// Fallback visual icons for standard roles until we support custom DB icons
export const ROLE_ICONS = {
  router: 'fa-network-wired',
  firewall: 'fa-shield-halved',
  switch: 'fa-server',
  access_point: 'fa-wifi',
  server: 'fa-server',
  hypervisor: 'fa-layer-group',
  nas: 'fa-hard-drive',
  storage: 'fa-hard-drive',
  compute: 'fa-microchip',
  desktop: 'fa-desktop',
  workstation: 'fa-desktop',
  mini_pc: 'fa-box',
  raspberry_pi: 'fa-raspberry-pi',
  sbc: 'fa-microchip',
  laptop: 'fa-laptop',
  ups: 'fa-battery-full',
  pdu: 'fa-plug',
  ip_camera: 'fa-video',
  phone: 'fa-mobile-screen',
  tablet: 'fa-tablet-screen-button',
  smart_tv: 'fa-tv',
  thermostat: 'fa-temperature-half',
  printer: 'fa-print',
  gaming_console: 'fa-gamepad',
  voip_phone: 'fa-phone',
  iot_device: 'fa-microchip',
  vm: 'fa-desktop',
  lxc: 'fa-box-open',
  misc: 'fa-microchip',
};
