export const VENDORS = [
  { value: 'amd',        label: 'AMD' },
  { value: 'intel',      label: 'Intel' },
  { value: 'nvidia',     label: 'Nvidia' },
  { value: 'arm',        label: 'ARM' },
  { value: 'apple',      label: 'Apple' },
  { value: 'dell',       label: 'Dell' },
  { value: 'hp',         label: 'HP' },
  { value: 'lenovo',     label: 'Lenovo' },
  { value: 'supermicro', label: 'Supermicro' },
  { value: 'asus',       label: 'ASUS' },
  { value: 'gigabyte',   label: 'Gigabyte' },
  { value: 'asrock',     label: 'ASRock' },
  { value: 'cisco',      label: 'Cisco' },
  { value: 'ubiquiti',   label: 'Ubiquiti' },
  { value: 'mikrotik',   label: 'MikroTik' },
  { value: 'synology',   label: 'Synology' },
  { value: 'qnap',       label: 'QNAP' },
  { value: 'proxmox',    label: 'Proxmox' },
  { value: 'pfsense',    label: 'pfSense' },
  { value: 'opnsense',   label: 'OPNsense' },
  { value: 'other',      label: 'Other / Generic' },
];
