"""Let retention actually purge, and give the fleet-wide discovery hold storage.

Revision ID: 0101_discovery_retention_and_global_pause
Revises: 0100_discovery_agent_execution
Create Date: 2026-08-09

Slice 4 Phase D remediation. Two independent defects that both survived behind
green gates, in one revision because both are one-column-shaped and neither can
be released without the other.

**A1 — `hardware.source_scan_result_id` becomes `ON DELETE SET NULL`.**
It shipped as a bare `ForeignKey("scan_results.id")`, i.e. NO ACTION, and every
approval path writes it (`discovery_merge.py`, `discovery_import_service.py`).
`discovery_scheduler._purge_old_scan_results_impl` therefore raised
`ForeignKeyViolation` as soon as any expiring result had been merged into
inventory; the purge body's own `except` swallowed it and rolled back, so
results, logs *and* jobs all survived. Retention has never happened for any
installation that ever approved a discovered device.

The pointer is *provenance*, not ownership: it records which scan result a
device was approved from, every reader already treats it as optional, and
inventory must not pin discovery history forever. The alternative — excluding
merged results from the purge — would make the rows most worth ageing out the
only ones that never age out.

**A2 — `app_settings.agent_discovery_paused` gets a real column.**
A name constant in `discovery_service` named it and it was read through
`getattr(settings, ..., False)` against a column that did not exist, so the
fleet-wide hold read `False` forever and only tests reaching past the mapper
could observe it as anything else. Task 26 / M14 requires pause/resume for all
three scopes; this is the storage for the third.

Both steps inspect first, so replaying is safe — and so is the fresh-install
path. Unlike `0100`'s columns, neither object here is one `0001_init` copies
*badly* (D-2), so neither needs an `_EXCLUDED_COLUMNS` entry:

* the FK's target table `scan_results` is not in `_EXCLUDED_TABLES` and its
  target column is not excluded, so `_should_copy_fk` keeps it and
  `_copy_column` carries `ondelete=fk.ondelete` verbatim — a fresh bootstrap
  gets SET NULL straight from `models.py`;
* `agent_discovery_paused` is a plain `Boolean NOT NULL DEFAULT '0'` with no FK
  and no index, which `_copy_column` reproduces exactly.

That is only safe because the two helpers below skip work already done. An
*unguarded* `op.add_column` is why every earlier `app_settings` column had to be
excluded from the bootstrap instead (`0002_discovery_engine.py:74-84`) — it
would raise `DuplicateColumn` on the fresh install where `0001_init` had already
created it.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect as sa_inspect

revision = "0101_discovery_retention_and_global_pause"
down_revision = "0100_discovery_agent_execution"
branch_labels = None
depends_on = None

_HARDWARE = "hardware"
_RESULTS = "scan_results"
_PROVENANCE_COLUMN = "source_scan_result_id"
#: `db/session.py`'s naming convention rendered for this constraint
#: (`fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s`). The *existing*
#: constraint is looked up by its columns rather than by this name, because an
#: install old enough to predate the convention would carry whatever alembic
#: autogenerated; the recreated one always gets the canonical name.
_PROVENANCE_FK = "fk_hardware_source_scan_result_id_scan_results"

_SETTINGS = "app_settings"
_PAUSE_COLUMN = "agent_discovery_paused"


def _provenance_fk(inspector: sa.Inspector) -> dict | None:
    for fk in inspector.get_foreign_keys(_HARDWARE):
        if fk["constrained_columns"] == [_PROVENANCE_COLUMN]:
            return fk
    return None


def _set_provenance_ondelete(ondelete: str | None) -> None:
    """Point `hardware.source_scan_result_id` at `scan_results.id` with *ondelete*.

    PostgreSQL has no `ALTER CONSTRAINT ... ON DELETE`, so the constraint is
    dropped and recreated. No data moves and no row is rewritten — only the
    catalog entry changes.
    """
    bind = op.get_bind()
    inspector = sa_inspect(bind)
    if _HARDWARE not in set(inspector.get_table_names()):
        return
    if _PROVENANCE_COLUMN not in {c["name"] for c in inspector.get_columns(_HARDWARE)}:
        return

    existing = _provenance_fk(inspector)
    if existing is not None:
        # Reflection omits `ondelete` entirely for NO ACTION, which is exactly
        # the state the downgrade restores — so `None` on both sides has to
        # compare equal rather than "unknown".
        current = (existing["options"].get("ondelete") or "").upper() or None
        if current == ondelete and existing["name"] == _PROVENANCE_FK:
            return
        op.drop_constraint(existing["name"], _HARDWARE, type_="foreignkey")

    op.create_foreign_key(
        _PROVENANCE_FK,
        _HARDWARE,
        _RESULTS,
        [_PROVENANCE_COLUMN],
        ["id"],
        ondelete=ondelete,
    )


def upgrade() -> None:
    _set_provenance_ondelete("SET NULL")

    inspector = sa_inspect(op.get_bind())
    if _PAUSE_COLUMN not in {c["name"] for c in inspector.get_columns(_SETTINGS)}:
        op.add_column(
            _SETTINGS,
            sa.Column(
                _PAUSE_COLUMN,
                sa.Boolean(),
                nullable=False,
                # NOT NULL on a table that already has its singleton row needs a
                # default to backfill from, and "not paused" is the only value
                # that preserves the behaviour of every install upgrading into
                # this revision.
                server_default="0",
            ),
        )


def downgrade() -> None:
    inspector = sa_inspect(op.get_bind())
    if _PAUSE_COLUMN in {c["name"] for c in inspector.get_columns(_SETTINGS)}:
        op.drop_column(_SETTINGS, _PAUSE_COLUMN)

    # A real downgrade, not a no-op: NO ACTION is what `0100` and everything
    # before it ran with, and leaving SET NULL behind would make the revision
    # irreversible in the one direction an operator rolls back for.
    _set_provenance_ondelete(None)
