data_directory = '/data/pgdata'
hba_file = '/data/pgdata/pg_hba.conf'
ident_file = '/data/pgdata/pg_ident.conf'
unix_socket_directories = '/data/run/postgresql'
listen_addresses = '127.0.0.1'
port = 5432
max_connections = 100
shared_buffers = 128MB
wal_level = 'replica'
synchronous_commit = on
fsync = on
full_page_writes = on
log_destination = 'stderr'
logging_collector = off
log_statement = 'none'
