# shellcheck shell=bash
# Release bundle signature verification.
#
# Shared by release.yml and release-dry-run.yml (sourced) and install.sh (an
# inlined copy, regenerated by scripts/ci/sync_installer_ui.py). Design:
# docs/design/2026-09-30-release-bundle-signing-design.md.
#
# Needs bash, coreutils and OpenSSL 3; no network.

CB_FIRST_SIGNED_RELEASE="0.4.7"

# DER SubjectPublicKeyInfo header for an Ed25519 key (RFC 8410). The raw
# 32-byte public key follows it; OpenSSL reads the pair as a DER public key.
_CB_ED25519_SPKI_PREFIX='\x30\x2a\x30\x05\x06\x03\x2b\x65\x70\x03\x21\x00'

# deploy/keys/release-bundle-keys.txt, verbatim.
_cb_embedded_release_keys() {
  cat <<'CB_RELEASE_KEYS'
# Trusted Ed25519 keys for Circuit Breaker release bundles (SHA256SUMS.sig).
# Format: <key-id> <base64 raw 32-byte public key> <first-version> <comment>
# key-id: first 16 hex characters of sha256(raw public key).
# install.sh and deploy/lib/bundle-signature.sh embed this file verbatim.
# Rotation adds a line; a line is removed only on compromise.
# See docs/release/bundle-signing.md.
CB_RELEASE_KEYS
}

# Print "<key-id> <base64 key>" for each trusted key whose id matches its key.
# $1: optional keys file; the embedded list otherwise. A malformed line is
# skipped: it can only ever fail to verify, never widen trust.
cb_release_keys() {
  local src line key_id key _rest raw_len actual
  if [[ -n "${1:-}" ]]; then
    src="$(cat -- "$1")" || return 1
  else
    src="$(_cb_embedded_release_keys)"
  fi
  while IFS= read -r line; do
    [[ -z "${line//[[:space:]]/}" || "$line" == \#* ]] && continue
    read -r key_id key _rest <<<"$line"
    [[ "$key_id" =~ ^[0-9a-f]{16}$ ]] || continue
    raw_len="$(printf '%s' "$key" | base64 -d 2>/dev/null | wc -c)" || continue
    [[ "$raw_len" -eq 32 ]] || continue
    actual="$(printf '%s' "$key" | base64 -d | sha256sum | cut -c1-16)"
    [[ "$actual" == "$key_id" ]] || continue
    printf '%s %s\n' "$key_id" "$key"
  done <<<"$src"
}

# Verify SHA256SUMS ($1) against SHA256SUMS.sig ($2) with the trusted keys
# ($3 optional keys file). Prints the id of the key that verified.
# 0: verified. 1: no trusted key verifies it. 2: the signature is unreadable,
# or there are no trusted keys at all.
cb_verify_sums_signature() {
  local sums="$1" sig="$2" keys_file="${3:-}" work key_id key tried=0 rc=1
  work="$(mktemp -d)" || return 2
  # Whitespace-insensitive: CRLF or trailing blanks from a copy must not
  # turn a good signature into "unreadable".
  if ! tr -d ' \t\r\n' <"$sig" | base64 -d >"$work/sig" 2>/dev/null \
    || [[ "$(wc -c <"$work/sig")" -ne 64 ]]; then
    rm -rf "$work"
    return 2
  fi
  while read -r key_id key; do
    tried=$((tried + 1))
    { printf '%b' "$_CB_ED25519_SPKI_PREFIX"; printf '%s' "$key" | base64 -d; } >"$work/pub.der"
    if openssl pkeyutl -verify -pubin -inkey "$work/pub.der" -keyform DER -rawin \
      -in "$sums" -sigfile "$work/sig" >/dev/null 2>&1; then
      printf '%s\n' "$key_id"
      rc=0
      break
    fi
  done < <(cb_release_keys "$keys_file")
  rm -rf "$work"
  if [[ "$tried" -eq 0 ]]; then
    return 2
  fi
  return "$rc"
}

# Check one tarball ($2) against its own line in SHA256SUMS ($1). The line is
# chosen by exact name (./<basename>), never with --ignore-missing, so a sums
# file that does not list this tarball cannot "verify" it.
# 0: match. 1: mismatch. 3: not listed.
cb_verify_sums_entry() {
  local sums="$1" tarball="$2" name expected actual
  name="$(basename -- "$tarball")"
  expected="$(awk -v want="./${name}" '$2 == want { print $1; exit }' "$sums")"
  [[ -n "$expected" ]] || return 3
  actual="$(sha256sum -- "$tarball" | cut -d' ' -f1)"
  [[ "$actual" == "$expected" ]] || return 1
}

# 0 when release $1 must carry a signature (it is CB_FIRST_SIGNED_RELEASE or
# later), 1 for earlier releases and for an empty version.
cb_release_requires_signature() {
  local v="${1#v}"
  [[ -n "$v" ]] || return 1
  [[ "$(printf '%s\n%s\n' "$CB_FIRST_SIGNED_RELEASE" "$v" | sort -V | head -n1)" == "$CB_FIRST_SIGNED_RELEASE" ]]
}
