#!/usr/bin/env python3
"""Assemble the hermetic application tree from python-build-standalone.

One tree is the product: the release tarball is this directory plus the
installer files, nfpm packs it to /opt/circuitbreaker, and Dockerfile.mono runs
this same file in a builder stage. Stdlib only, deliberately — that Docker stage
has no repo venv, and the tree must not depend on whatever happens to be
installed on the build host.

Why not PyInstaller: it builds from a static import graph, so a module named
only by a string is dropped silently (v0.4.2 shipped with no `app.main`;
gh#104 shipped with no `proxmoxer.backends`), and its --onefile mode extracts
itself into $TMPDIR on every process start (AGT-11). Here the packages are
present as packages, and nothing is extracted at run time.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import platform
import re
import shutil
import subprocess
import sys
import tarfile
import urllib.request
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PIN_FILE = REPO_ROOT / "packaging" / "python-build-standalone.pin"
BACKEND_ROOT = REPO_ROOT / "apps" / "backend"
VERSION_FILE = REPO_ROOT / "VERSION"

REQUIREMENT_FILES: tuple[Path, ...] = (
    BACKEND_ROOT / "requirements.txt",
    BACKEND_ROOT / "requirements-pg.txt",
    BACKEND_ROOT / "requirements-acme.txt",
)
PBS_TRIPLES = {"amd64": "x86_64-unknown-linux-gnu", "arm64": "aarch64-unknown-linux-gnu"}
PBS_FLAVOUR = "install_only_stripped"
PBS_BASE_URL = "https://github.com/astral-sh/python-build-standalone/releases/download"
RUNTIME = "pbs"
# Local wheels for pure-Python packages PyPI only publishes as sdists. pip's
# --only-binary=:all: refuses those; vendoring a wheel here (built once, no
# compiler) keeps the install wheels-only without weakening the gate. Every
# ``*.whl`` must have a sibling ``*.whl.sha256`` content digest; install refuses
# an unhashed or mismatched wheel the same way fetch_interpreter refuses a
# mismatched PBS archive.
LOCAL_WHEELS = REPO_ROOT / "packaging" / "wheels"
# What the digest covers: the interpreter, the launchers and the migration
# entrypoint. Not share/frontend (a Vite build is not the runtime) and not
# agent-binaries (Go, signed separately).
DIGEST_ROOTS = ("python", "bin", "share/backend")
_NO_BYTECODE = shutil.ignore_patterns("__pycache__", "*.pyc", "*.pyo")
_GLIBC_RE = re.compile(rb"GLIBC_(\d+)\.(\d+)")

LAUNCHER = """\
#!/bin/sh
# Generated by scripts/pbs_tree.py. The only entrypoint into the tree.
#   -I  isolated: no PYTHONPATH/PYTHONHOME, no user site, no cwd on sys.path
#   -B  never write bytecode; the tree was compiled by this interpreter at build
#   -X utf8  the same UTF-8 guarantee start.py used to set for its children
# CB_SHARE_DIR is how app.core.config and app.startup.paths find share/ now
# that sys.executable is the bundled interpreter, not a file beside share/.
self="$(readlink -f "$0")"
root="$(cd "$(dirname "$self")/.." && pwd)"
export CB_APP_ROOT="$root"
: "${CB_SHARE_DIR:=$root/share}"
export CB_SHARE_DIR
exec "$root/python/bin/python3" -I -B -X utf8 -m app.start "$@"
"""

CB_PYTHON = """\
#!/bin/sh
# Generated by scripts/pbs_tree.py. The tree's interpreter with the same
# isolation as bin/circuit-breaker, for callers that need a module other than
# app.start: the mono image's `-m uvicorn`, `-m app.workers.main`, `-m alembic`
# and `-m certbot`. pip's console scripts are deleted from the tree because
# their shebangs would embed the build path; this is what replaces them.
self="$(readlink -f "$0")"
root="$(cd "$(dirname "$self")/.." && pwd)"
export CB_APP_ROOT="$root"
: "${CB_SHARE_DIR:=$root/share}"
export CB_SHARE_DIR
exec "$root/python/bin/python3" -I -B -X utf8 "$@"
"""


@dataclass(frozen=True)
class PbsPin:
    """The pinned interpreter: release tag, CPython version, digest per arch."""

    release: str
    python: str
    sha256: dict[str, str]


def read_pin(path: Path = PIN_FILE) -> PbsPin:
    """Parse the KEY=VALUE pin file; every field is required."""
    values: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        if "=" in line:
            key, _, value = line.partition("=")
            values[key.strip()] = value.strip()
    missing = [k for k in ("PBS_RELEASE", "PBS_PYTHON", "PBS_SHA256_amd64", "PBS_SHA256_arm64") if not values.get(k)]
    if missing:
        raise SystemExit(f"{path} is missing {', '.join(missing)}")
    return PbsPin(
        release=values["PBS_RELEASE"],
        python=values["PBS_PYTHON"],
        sha256={"amd64": values["PBS_SHA256_amd64"].lower(), "arm64": values["PBS_SHA256_arm64"].lower()},
    )


def asset_name(pin: PbsPin, arch: str) -> str:
    """The distributor's file name for this pin and architecture."""
    return f"cpython-{pin.python}+{pin.release}-{PBS_TRIPLES[arch]}-{PBS_FLAVOUR}.tar.gz"


def asset_url(pin: PbsPin, arch: str) -> str:
    """Where the distributor publishes that file."""
    return f"{PBS_BASE_URL}/{pin.release}/{asset_name(pin, arch)}"


def sha256_file(path: Path) -> str:
    """Hex SHA-256 of a file, streamed."""
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def fetch_interpreter(pin: PbsPin, arch: str, cache_dir: Path) -> Path:
    """Download the pinned archive into cache_dir, verifying the pinned digest.

    A cached file is reused only if it still matches the pin, so bumping the
    pin invalidates the cache by construction. A mismatch is deleted, not
    cached, so a corrupt download cannot be "verified" on the next run.
    """
    cache_dir.mkdir(parents=True, exist_ok=True)
    archive = cache_dir / asset_name(pin, arch)
    expected = pin.sha256[arch]
    if archive.exists() and sha256_file(archive) == expected:
        return archive
    partial = archive.with_suffix(".part")
    print(f"  Fetching {asset_name(pin, arch)}")
    urllib.request.urlretrieve(asset_url(pin, arch), partial)
    actual = sha256_file(partial)
    if actual != expected:
        partial.unlink()
        raise SystemExit(
            f"python-build-standalone digest mismatch for {asset_name(pin, arch)}:\n"
            f"  expected {expected}\n  actual   {actual}\n"
            "Refusing to build a tree on an unverified interpreter."
        )
    partial.replace(archive)
    return archive


def unpack_interpreter(archive: Path, tree: Path) -> Path:
    """Extract the archive's single `python/` root into tree; return python3."""
    with tarfile.open(archive) as tar:
        members = tar.getmembers()
        if not members or any(not (m.name == "python" or m.name.startswith("python/")) for m in members):
            raise SystemExit(f"{archive.name} is not an install_only archive: expected every member under python/")
        tree.mkdir(parents=True, exist_ok=True)
        tar.extractall(tree, filter="data")
    python = tree / "python" / "bin" / "python3"
    if not python.exists():
        raise SystemExit(f"{archive.name} unpacked without python/bin/python3")
    return python


def site_packages(tree: Path) -> Path:
    """The interpreter's own site-packages; exactly one must exist."""
    found = sorted((tree / "python" / "lib").glob("python3.*/site-packages"))
    if len(found) != 1:
        raise SystemExit(f"expected one site-packages under {tree / 'python' / 'lib'}, found {found}")
    return found[0]


def _run(cmd: list[str], **kwargs: object) -> None:
    subprocess.run(cmd, check=True, **kwargs)  # type: ignore[call-overload]


def verify_local_wheels(wheels_dir: Path = LOCAL_WHEELS) -> None:
    """Refuse any committed wheel whose content does not match its .sha256 sidecar.

    Digests are content hashes of the wheel bytes we committed — the same
    "never trust an unverified input" rule as PBS pins. A wheel without a
    sidecar, or with a stale one, fails here rather than being installed.
    """
    if not wheels_dir.is_dir():
        return
    wheels = sorted(wheels_dir.glob("*.whl"))
    if not wheels:
        return
    for wheel in wheels:
        sidecar = Path(str(wheel) + ".sha256")
        if not sidecar.is_file():
            raise SystemExit(
                f"vendored wheel {wheel.name} has no {sidecar.name} content digest; "
                "refuse to install an unpinned build input"
            )
        expected = sidecar.read_text(encoding="utf-8").split()[0].strip().lower()
        actual = sha256_file(wheel)
        if actual != expected:
            raise SystemExit(
                f"vendored wheel digest mismatch for {wheel.name}:\n"
                f"  expected {expected}\n  actual   {actual}\n"
                "Refusing to build a tree on an unverified local wheel."
            )


def install_dependencies(tree: Path, requirement_files: tuple[Path, ...]) -> None:
    """pip-install the committed pins with the tree's own interpreter, wheels only.

    --no-deps: requirements.txt is a full transitive freeze of poetry.lock, so
    resolution would only ever add something the lock did not say.
    --only-binary=:all:: a package with no wheel for this interpreter and arch
    fails here, loudly, and is fixed by pinning — not by adding a compiler to
    the build and hoping the sdist builds the same way twice.
    --no-compile: bytecode is written once, later, by compile_bytecode, with a
    deterministic invalidation mode.
    """
    python = str(tree / "python" / "bin" / "python3")
    pip = [python, "-m", "pip", "--disable-pip-version-check", "--no-cache-dir"]
    if subprocess.run([*pip, "--version"], capture_output=True, check=False).returncode != 0:
        _run([python, "-m", "ensurepip", "--upgrade"])
    args: list[str] = []
    for path in requirement_files:
        if not path.is_file():
            raise SystemExit(f"requirement file missing: {path}")
        args += ["-r", str(path)]
    find_links: list[str] = []
    if LOCAL_WHEELS.is_dir() and any(LOCAL_WHEELS.glob("*.whl")):
        verify_local_wheels(LOCAL_WHEELS)
        find_links = ["--find-links", str(LOCAL_WHEELS)]
    _run([*pip, "install", "--no-deps", "--only-binary=:all:", "--no-compile", *find_links, *args])
    site = site_packages(tree)
    shutil.copytree(BACKEND_ROOT / "src" / "app", site / "app", ignore=_NO_BYTECODE)


def prune_tree(tree: Path) -> None:
    """Remove what must not ship: installers, build-path-bearing metadata, dev cruft.

    pip and setuptools: nothing installs packages at run time, and pip's
    vendored dependency set is reported by every image scanner (Dockerfile.mono
    removes pip for the same reason).
    Console scripts: pip writes their shebang as the absolute path of the
    interpreter at install time — the build directory — so a relocated tree
    would exec a path that does not exist. bin/cb-python replaces them.
    direct_url.json: records the source path of a local install; it differs
    between the native build and the Docker stage and would break the digest
    parity the two are held to.
    """
    site = site_packages(tree)
    for pattern in (
        "pip", "pip-*.dist-info", "setuptools", "setuptools-*.dist-info", "pkg_resources",
        "_distutils_hack", "distutils-precedence.pth", "wheel", "wheel-*.dist-info",
    ):
        for path in site.glob(pattern):
            shutil.rmtree(path) if path.is_dir() else path.unlink()
    for path in list(site.rglob("direct_url.json")):
        path.unlink()
    bin_dir = tree / "python" / "bin"
    for path in list(bin_dir.iterdir()):
        if not path.name.startswith("python"):
            path.unlink()
    lib = site.parent
    for rel in ("test", "idlelib", "ensurepip", "tkinter", "turtledemo"):
        shutil.rmtree(lib / rel, ignore_errors=True)
    for rel in ("include", "share"):
        shutil.rmtree(tree / "python" / rel, ignore_errors=True)
    for path in list((tree / "python").rglob("__pycache__")):
        shutil.rmtree(path, ignore_errors=True)


def compile_bytecode(tree: Path) -> None:
    """Precompile with the shipped interpreter, hash-validated, so /opt can be read-only.

    unchecked-hash pycs embed the source hash rather than an mtime, which is
    what makes two builds of the same inputs byte-identical and what lets the
    service run under ProtectSystem=strict without ever wanting to write one.
    """
    python = str(tree / "python" / "bin" / "python3")
    _run([python, "-m", "compileall", "-q", "-j", "0", "--invalidation-mode", "unchecked-hash",
          str(tree / "python" / "lib")])


def write_launchers(tree: Path) -> None:
    """bin/circuit-breaker and bin/cb-python, mode 0755."""
    bin_dir = tree / "bin"
    bin_dir.mkdir(parents=True, exist_ok=True)
    for name, text in (("circuit-breaker", LAUNCHER), ("cb-python", CB_PYTHON)):
        path = bin_dir / name
        path.write_text(text, encoding="utf-8")
        path.chmod(0o755)


def glibc_floor(tree: Path) -> str:
    """The highest GLIBC_x.y any ELF under python/ references — the real floor.

    A PyInstaller bundle inherited its build host's floor; a PBS tree has one
    that can be read off the artifact. Read from the bytes rather than via
    readelf so the Docker stage needs no binutils and both builds agree.
    """
    best = (0, 0)
    for path in (tree / "python").rglob("*"):
        if not path.is_file() or path.is_symlink():
            continue
        with path.open("rb") as handle:
            if handle.read(4) != b"\x7fELF":
                continue
        for match in _GLIBC_RE.finditer(path.read_bytes()):
            best = max(best, (int(match.group(1)), int(match.group(2))))
    if best == (0, 0):
        raise SystemExit(f"no GLIBC_ version symbols under {tree / 'python'}; not a linux-gnu tree?")
    return f"{best[0]}.{best[1]}"


def runtime_digest(tree: Path) -> str:
    """Content digest of DIGEST_ROOTS: paths and bytes, never mtimes or modes."""
    digest = hashlib.sha256()
    for root in DIGEST_ROOTS:
        base = tree / root
        if not base.exists():
            continue
        for path in sorted(p for p in base.rglob("*") if p.is_file() or p.is_symlink()):
            digest.update(path.relative_to(tree).as_posix().encode())
            digest.update(b"\0")
            if path.is_symlink():
                digest.update(b"L" + os.readlink(path).encode())
            else:
                digest.update(b"F" + sha256_file(path).encode())
            digest.update(b"\n")
    return digest.hexdigest()


def lock_sha256(requirement_files: tuple[Path, ...]) -> str:
    """One digest over the pins the tree was built from, in order."""
    digest = hashlib.sha256()
    for path in requirement_files:
        digest.update(path.read_bytes())
        digest.update(b"\n--\n")
    return digest.hexdigest()


def write_build_info(tree: Path, *, version: str, arch: str, pin: PbsPin, requirement_files: tuple[Path, ...]) -> None:
    """share/build-info.json: provenance read from inside the artifact under test."""
    floor = glibc_floor(tree)
    distro = "unknown"
    os_release = Path("/etc/os-release")
    if os_release.is_file():
        fields = dict(
            (line.partition("=")[0], line.partition("=")[2].strip().strip('"'))
            for line in os_release.read_text(encoding="utf-8").splitlines() if "=" in line
        )
        distro = f"{fields.get('ID', 'unknown')}-{fields.get('VERSION_ID', '')}".rstrip("-")
    in_ci = os.environ.get("GITHUB_ACTIONS", "").lower() == "true"
    info = {
        "version": version,
        "os": "linux",
        "arch": arch,
        "built_by": "ci" if in_ci else "local",
        "glibc": floor,
        "glibc_floor": floor,
        "distro": distro,
        "python": pin.python,
        "runtime": RUNTIME,
        "pbs_release": pin.release,
        "pbs_sha256": pin.sha256[arch],
        "lock_sha256": lock_sha256(requirement_files),
        "runtime_digest": runtime_digest(tree),
        "ci_run": os.environ.get("GITHUB_RUN_ID", ""),
        "ci_workflow": os.environ.get("GITHUB_WORKFLOW", ""),
        "commit": os.environ.get("GITHUB_SHA", ""),
    }
    (tree / "share" / "build-info.json").write_text(json.dumps(info, indent=2) + "\n", encoding="utf-8")


def assert_tree_contains_application(tree: Path) -> None:
    """Run the launcher's --selftest; refuse the tree if it cannot import the app."""
    launcher = tree / "bin" / "circuit-breaker"
    print(f"Verifying {launcher} contains its application...")
    completed = subprocess.run(
        [str(launcher), "--selftest"], capture_output=True, text=True, timeout=300, check=False,
        env={**os.environ, "CB_DB_URL": "postgresql://fake:fake@localhost/fake"},
    )
    output = (completed.stdout + completed.stderr).strip()
    if completed.returncode != 0:
        raise SystemExit(
            f"the tree failed its self-test (exit {completed.returncode}).\n{output}\n\n"
            "A module the application needs is missing from site-packages: a pin absent from "
            "apps/backend/requirements*.txt, or a wheel that did not install. Refusing to stage it."
        )
    print(f"  {output}")


def build_tree(
    *,
    arch: str,
    version: str,
    output: Path,
    cache_dir: Path,
    frontend_dist: Path | None,
    agent_dist: Path | None,
    requirement_files: tuple[Path, ...] = REQUIREMENT_FILES,
) -> Path:
    """Assemble a fresh tree at output and prove it; returns output."""
    if arch not in PBS_TRIPLES:
        raise SystemExit(f"unsupported architecture {arch!r}; python-build-standalone pins exist for {sorted(PBS_TRIPLES)}")
    pin = read_pin()
    if output.exists():
        shutil.rmtree(output)
    output.mkdir(parents=True)
    unpack_interpreter(fetch_interpreter(pin, arch, cache_dir), output)
    install_dependencies(output, requirement_files)
    prune_tree(output)
    compile_bytecode(output)
    write_launchers(output)

    share = output / "share"
    backend_share = share / "backend"
    backend_share.mkdir(parents=True)
    (share / "VERSION").write_text(version.strip() + "\n", encoding="utf-8")
    shutil.copy2(BACKEND_ROOT / "alembic.ini", backend_share / "alembic.ini")
    shutil.copytree(BACKEND_ROOT / "migrations", backend_share / "migrations", ignore=_NO_BYTECODE)
    if frontend_dist is not None:
        shutil.copytree(frontend_dist, share / "frontend")
    if agent_dist is not None and agent_dist.exists():
        shutil.copytree(agent_dist, output / "agent-binaries")
    write_build_info(output, version=version, arch=arch, pin=pin, requirement_files=requirement_files)
    assert_tree_contains_application(output)
    return output


def default_arch() -> str:
    """This host's architecture in the amd64/arm64 vocabulary the pins use."""
    machine = platform.machine().lower()
    mapping = {"x86_64": "amd64", "amd64": "amd64", "aarch64": "arm64", "arm64": "arm64"}
    if machine not in mapping:
        raise SystemExit(f"unsupported build host architecture {machine!r}")
    return mapping[machine]


def main(argv: list[str] | None = None) -> int:
    """CLI used by Dockerfile.mono; build_native_release.py imports build_tree directly."""
    parser = argparse.ArgumentParser(description="Assemble the hermetic Circuit Breaker runtime tree.")
    parser.add_argument("--arch", default=default_arch(), choices=sorted(PBS_TRIPLES))
    parser.add_argument("--version", default=VERSION_FILE.read_text(encoding="utf-8").strip())
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--cache-dir", type=Path, default=REPO_ROOT / "build" / "pbs-cache")
    parser.add_argument("--frontend-dist", type=Path, default=None)
    parser.add_argument("--agent-dist", type=Path, default=None)
    args = parser.parse_args(argv)
    tree = build_tree(
        arch=args.arch, version=args.version, output=args.output, cache_dir=args.cache_dir,
        frontend_dist=args.frontend_dist, agent_dist=args.agent_dist,
    )
    print(tree)
    return 0


if __name__ == "__main__":
    sys.exit(main())
